// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

// TASKS
export const INIT_TASKS = "INIT_TASKS";
export const POST_NEW_TASK = "POST_NEW_TASK";
export const GET_TASKS_FOR_WEEK = "GET_TASKS_FOR_WEEK";
export const GET_MONTHLY_SUMS = "GET_MONTHLY_SUMS";
export const DELETE_TASK = "DELETE_TASK";

// TODOS
export const GET_TODOS_FOR_WEEK = "GET_TODOS_FOR_WEEK";
export const CREATE_NEW_TODO = "CREATE_NEW_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";

// WEEKS & DATES
export const SET_DATE = "SET_DATE";
