import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import 'bootstrap/dist/css/bootstrap.min.css';
// import "bootstrap/dist/css/bootstrap.css";
import "font-awesome/css/font-awesome.css";
import "pretty-checkbox/dist/pretty-checkbox.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min";
import 'typeface-roboto';
ReactDOM.render(<App />, document.getElementById("root"));
